---
os: linux
language: python

addons:
  apt:
    packages:
      libdbus-glib-1-dev

branches:
  only:
    - master

jobs:
  include:

    # MANDATORY CHECKS USING CURRENT DEVELOPMENT INTERPRETER
    - name: "run pylint using Python 3.7.7"
      python: "3.7.7"
      install:
        - >
          pip
          install
          pylint==2.4.4
          dbus-client-gen==0.4
          dbus-python-client-gen==0.7
          justbytes==0.11
          python-dateutil==2.8.0
          wcwidth==0.1.9
          psutil==5.6.7
          semantic_version==2.6.0
      script: PYTHONPATH=./src make -f Makefile lint
    - name: "check formatting using Python 3.7.7"
      python: "3.7.7"
      install: pip install black==19.10b0 isort==4.3.21
      env: TASK=fmt-travis
    - name: "run tests that do not require stratisd using Python 3.7.7"
      python: "3.7.7"
      install:
        - >
          pip
          install
          dbus-client-gen==0.4
          dbus-python-client-gen==0.7
          justbytes==0.11
          python-dateutil==2.8.0
          wcwidth==0.1.9
          psutil==5.6.7
          semantic_version==2.6.0
      script: PYTHONPATH=./src make -f Makefile test-travis

    # MANDATORY CHECKS USING LOWEST SUPPORTED INTERPRETER
    - name: "run pylint using Python 3.6.8, omit optional wcwidth dependency"
      python: "3.6.8"
      install:
        - >
          pip
          install
          pylint==2.4.4
          dbus-client-gen==0.4
          dbus-python-client-gen==0.7
          justbytes==0.11
          python-dateutil==2.6.1
          psutil==5.4.3
          semantic_version==2.6.0
      script: PYTHONPATH=./src make -f Makefile lint

    # VERIFICATION OF TEST INFRASTRUCTURE
    - name: "run yamllint 1.23.0 on .travis.yml"
      python: "3.7.7"
      install: pip install yamllint==1.23.0
      env: TASK=yamllint

script: make -f Makefile $TASK
