---
os: linux
language: python

addons:
  apt:
    packages:
      libdbus-glib-1-dev

branches:
  only:
    - master
    - develop-2.0.1

jobs:
  include:

    # MANDATORY CHECKS USING CURRENT DEVELOPMENT INTERPRETER
    - name: "run pylint using Python 3.7.6"
      python: "3.7.6"
      install:
        - >
          pip
          install
          pylint==2.3.1
          dbus-client-gen==0.4
          dbus-python-client-gen==0.7
          justbytes==0.11
          python-dateutil==2.8.0
          wcwidth==0.1.7
          psutil==5.4.3
          semantic_version==2.8.5
      script: PYTHONPATH=./src make -f Makefile lint
    - name: "check formatting using Python 3.7.6"
      python: "3.7.6"
      install: pip install black==19.3b0 isort==4.3.4
      env: TASK=fmt-travis
    - name: "run tests that do not require stratisd using Python 3.7.6"
      python: "3.7.6"
      install:
        - >
          pip
          install
          dbus-client-gen==0.4
          dbus-python-client-gen==0.7
          justbytes==0.11
          python-dateutil==2.8.0
          wcwidth==0.1.7
          psutil==5.4.3
          semantic_version==2.8.5
      script: PYTHONPATH=./src make -f Makefile test-travis

    # MANDATORY CHECKS USING LOWEST SUPPORTED INTERPRETER
    - name: "run pylint using Python 3.6.8"
      python: "3.6.8"
      install:
        - >
          pip
          install
          pylint==2.3.1
          dbus-client-gen==0.4
          dbus-python-client-gen==0.7
          justbytes==0.11
          python-dateutil
          wcwidth
          psutil
          semantic_version=2.8.5
      script: PYTHONPATH=./src make -f Makefile lint

    # VERIFICATION OF TEST INFRASTRUCTURE
    - name: "run yamllint on .travis.yml"
      python: "3.7.6"
      install: pip install yamllint
      script: yamllint .travis.yml

script: make -f Makefile $TASK
